#!/usr/bin/env bash
#Runs a node script or npm command in a docker container interactively. The first arg
#should be the path to a script relative to the pwd or 'npm'. The current user/group
#are injected into the container so you can do an npm install and get the right file
#permissions
ADD_USER_SCRIPT="addgroup -g $(id -g) $(id -gn); adduser -D -u $(id -u) -G $(id -gn) $(id -un) -s /bin/sh; su $(id -un) -c 'mkdir -p ./build/.tmp/.npm'; npm config set prefix './build/.tmp/.npm'"
NODE_COMMAND="node $1 ${@:2}"
if [[ "$1" = "npm" ]]; then
  NODE_COMMAND="npm ${@:2}"
fi
if [[ -e "$(pwd)/.nvmrc" ]]; then
  NODE_VERSION=$(cat $(pwd)/.nvmrc)
elif [[ -z $NODE_VERSION ]]; then
  NODE_VERSION=6.3.1
fi
COMMAND="$ADD_USER_SCRIPT; su $(id -un) -c '$NODE_COMMAND'"
docker run -i --net=host --rm -v="$(pwd):/code" -w="/code" mhart/alpine-node:$NODE_VERSION /bin/sh -c "$COMMAND"
